import {config} from '../config/app.ts';
import {demoUser,historySeed,locations,services,providers,trackingOffsets,providerJob} from '../data/mockData.ts';
import type {AppState,Draft,Request,Status,User} from '../types/index.ts';
const initial:AppState = {authenticated:false,pendingPhone:'',user:structuredClone(demoUser),requests:structuredClone(historySeed),activeId:null,draft:{serviceId:'towing',vehicle:structuredClone(demoUser.vehicle),problem:'',location:locations[0]},offline:false,failPayment:false,paused:false,theme:'light',sos:null};
let state:AppState;
try {const saved=JSON.parse(localStorage.getItem(config.storageKey)||'null');state=saved?{...initial,...saved,offline:false}:initial;}catch{state=initial;}
const listeners = new Set<()=>void>();
export const store = {get:()=>state,subscribe:(listener:()=>void)=>{listeners.add(listener);return()=>listeners.delete(listener);},set:(patch:Partial<AppState>)=>{state={...state,...patch};try{localStorage.setItem(config.storageKey,JSON.stringify(state));}catch{}listeners.forEach(fn=>fn());}};
const wait = (ms=config.simulation.delay)=>new Promise<void>(resolve=>setTimeout(resolve,ms));
async function operation(){await wait();if(state.offline||!navigator.onLine)throw new Error('You’re offline. Restore your connection and try again.');}
function updateRequest(id:string,patch:Partial<Request>){const req=state.requests.find(r=>r.id===id);if(!req)throw new Error('Request not found. Return to your request history.');store.set({requests:state.requests.map(r=>r.id===id?{...r,...patch}:r)});return {...req,...patch};}
export const getActive = ()=>state.requests.find(r=>r.id===state.activeId)||null;
export function getTrackingData(request:Request){const points=trackingOffsets.map(([a,b])=>[request.location.coordinates[0]+a,request.location.coordinates[1]+b] as [number,number]);const position=Math.min(request.progress,1)*(points.length-1);const i=Math.min(Math.floor(position),points.length-2);const f=position-i;return {route:points,position:[points[i][0]+(points[i+1][0]-points[i][0])*f,points[i][1]+(points[i+1][1]-points[i][1])*f] as [number,number],eta:Math.max(0,Math.ceil((1-request.progress)*8))};}
export const api = {
 async login(phone:string){await operation();const cleaned=phone.replace(/\D/g,'').replace(/^0/,'');if(!/^[789]\d{9}$/.test(cleaned))throw new Error('Enter a valid Nigerian mobile number (10 digits after +234).');store.set({pendingPhone:config.countryCode+cleaned});return true;},
 async verifyOtp(code:string){await operation();if(!state.pendingPhone)throw new Error('Please enter your phone number first.');if(code!==config.otp)throw new Error('That code doesn’t match. Use the displayed demo OTP.');store.set({authenticated:true,user:{...state.user,phone:state.pendingPhone}});},
 logout(){store.set({authenticated:false,pendingPhone:''});},
 saveDraft(patch:Partial<Draft>){store.set({draft:{...state.draft,...patch}});},
 estimate(id=state.draft.serviceId){const service=services.find(s=>s.id===id)||services[0];return {service,base:service.base,distance:service.distanceCharge,total:service.base+service.distanceCharge};},
 async createRequest(){await operation();const current=getActive();if(current&&current.status!=='cancelled'&&(current.status!=='completed'||!current.payment))return current;const draft=state.draft;const request:Request={...structuredClone(draft),id:`ADR-${new Date().getFullYear()}-${String(Date.now()).slice(-8)}`,createdAt:new Date().toISOString(),status:'searching',total:this.estimate().total,providerId:null,progress:0,stageTicks:0};store.set({requests:[request,...state.requests],activeId:request.id});return request;},
 async findProvider(){await operation();const r=getActive();if(!r)throw new Error('Create a request first.');return updateRequest(r.id,{providerId:providers[0].id,status:'assigned',stageTicks:0});},
 async cancelRequest(id:string){await operation();const r=state.requests.find(x=>x.id===id);if(!r||['completed','cancelled','servicing'].includes(r.status))throw new Error('This request can no longer be cancelled.');return updateRequest(id,{status:'cancelled',stageTicks:0});},
 async acceptJob(){await operation();let r=getActive();if(!r||r.status==='completed'||r.status==='cancelled'){this.saveDraft({serviceId:providerJob.serviceId,location:providerJob.location,problem:providerJob.problem});r=await this.createRequest();}return updateRequest(r.id,{status:'enroute',providerId:providers[0].id,stageTicks:0});},
 async setJobStatus(status:Status){await operation();const r=getActive();if(!r)throw new Error('There is no active job.');const allowed:Record<string,string[]>= {searching:['assigned','enroute'],assigned:['enroute'],enroute:['arrived'],arriving:['arrived'],arrived:['servicing'],servicing:['completed']};if(!allowed[r.status]?.includes(status))throw new Error('Complete the current step before continuing.');return updateRequest(r.id,{status,stageTicks:0,...(['arrived','servicing','completed'].includes(status)?{progress:1}:{})});},
 async completeJob(){await operation();const r=getActive();if(!r||r.status==='cancelled')throw new Error('No active request to complete.');return updateRequest(r.id,{status:'completed',progress:1,stageTicks:0,providerId:r.providerId||providers[0].id});},
 async makePayment(method:string){await operation();if(state.failPayment)throw new Error('Demo payment declined. Turn off “Fail payment” in demo controls, then retry. No money was taken.');const r=getActive();if(!r||r.status!=='completed')throw new Error('Payment is available after your service is completed.');if(r.payment)return r;if(!['Bank Transfer','Card','Cash'].includes(method))throw new Error('Choose a payment method.');return updateRequest(r.id,{payment:{id:`PAY-${Date.now()}`,method,paidAt:new Date().toISOString()}});},
 async submitRating(rating:number,review:string){await operation();const r=getActive();if(!r?.payment)throw new Error('Complete payment first.');if(rating<1||rating>5)throw new Error('Choose a rating from 1 to 5 stars.');return updateRequest(r.id,{rating,review});},
 async getHistory(){await operation();return state.requests;},
 async saveProfile(user:User){await operation();if(!user.name.trim())throw new Error('Please enter your name.');store.set({user,draft:{...state.draft,vehicle:user.vehicle}});},
 async shareSOS(){await operation();const contacts=state.user.contacts.length;if(!contacts)throw new Error('Add an emergency contact in Profile first.');const sos={at:new Date().toISOString(),location:state.draft.location.address,contacts};store.set({sos});return sos;},
 async retryConnection(){await wait();if(!navigator.onLine)throw new Error('Your device is still offline. Check Wi-Fi or mobile data.');store.set({offline:false});},
 reset(){store.set(structuredClone(initial));},
};
export function advanceSimulation(){if(state.offline||state.paused||!navigator.onLine)return;const r=getActive();if(!r||['completed','cancelled'].includes(r.status))return;const ticks=r.stageTicks+1;let patch:Partial<Request>={stageTicks:ticks};if(r.status==='searching'&&ticks>=config.simulation.searchingTicks)patch={status:'assigned',providerId:providers[0].id,stageTicks:0};else if(r.status==='assigned'&&ticks>=config.simulation.assignedTicks)patch={status:'enroute',stageTicks:0};else if(['enroute','arriving'].includes(r.status)){const progress=Math.min(1,r.progress+1/config.simulation.routeTicks);patch={progress,stageTicks:ticks,status:progress>=1?'arrived':progress>.8?'arriving':'enroute'};if(progress>=1)patch.stageTicks=0;}else if(r.status==='arrived'&&ticks>=5)patch={status:'servicing',stageTicks:0};else if(r.status==='servicing'&&ticks>=config.simulation.serviceTicks)patch={status:'completed',stageTicks:0};updateRequest(r.id,patch);}
let timer:ReturnType<typeof setInterval>|undefined;
export function startSimulation(){if(!timer)timer=setInterval(advanceSimulation,config.simulation.tick);return()=>{clearInterval(timer);timer=undefined;};}
window.addEventListener('storage',e=>{if(e.key===config.storageKey&&e.newValue){try{state=JSON.parse(e.newValue);listeners.forEach(fn=>fn());}catch{}}});
