import React,{useEffect,useState} from 'react';
import {useParams} from 'react-router-dom';
import {api,store} from '../services/mockService.ts';
import {useApp,useTask} from '../hooks/useApp.ts';
import {services,statusLabels} from '../data/mockData.ts';
import {date} from '../config/app.ts';
import {Badge,ButtonLink,Card,EmptyState,ErrorMessage,Icon,PageHeading,PriceBreakdown,ProviderCard,RequestCard,Skeleton} from '../components/ui.tsx';
export function History(){const state=useApp();const task=useTask();const [filter,setFilter]=useState('All requests');const [query,setQuery]=useState('');const [loaded,setLoaded]=useState(false);const load=()=>task.run(()=>api.getHistory(),()=>setLoaded(true));useEffect(()=>{load();},[]);const list=state.requests.filter(r=>(filter==='All requests'||(filter==='Completed'?r.status==='completed':filter==='Cancelled'?r.status==='cancelled':!['completed','cancelled'].includes(r.status)))&&(`${services.find(s=>s.id===r.serviceId)?.name} ${r.location.address} ${r.id}`).toLowerCase().includes(query.toLowerCase()));return <><PageHeading eyebrow="EVERY JOURNEY HAS A STORY" title="Your requests, all in one place." description="A record of the helping hands that got you moving again." action={<ButtonLink to="/services" icon="Plus">New request</ButtonLink>}/><Card className="history-panel"><div className="history-toolbar"><div className="tabs" aria-label="Filter requests">{['All requests','Completed','Pending','Cancelled'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f} aria-pressed={filter===f}>{f}</button>)}</div><div className="search-field"><Icon name="Search" size={18}/><input aria-label="Search requests" placeholder="Search your requests" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><ErrorMessage message={task.error} retry={load}/>{task.loading?<Skeleton lines={4}/>:loaded?(list.length?list.map(r=><RequestCard request={r} key={r.id}/>):<EmptyState icon="History" title="No requests found" description="Try another filter or start a new request."/>):null}</Card><p className="fine-print">Your demo request history is saved in this browser. The initial example requests are fictional.</p></>;}
export function HistoryDetail(){const state=useApp();const {id}=useParams();const request=state.requests.find(r=>r.id===id);if(!request)return <EmptyState title="We couldn’t find that request." action="Back to history" to="/history"/>;const service=services.find(s=>s.id===request.serviceId)!;return <><PageHeading eyebrow="REQUEST DETAILS" title={service.name} description={`${request.id} · ${date(request.createdAt)}`} action={<ButtonLink variant="secondary" to="/history" icon="ArrowLeft">Back to history</ButtonLink>}/><div className="flow-grid"><Card><Badge tone={request.status==='cancelled'?'neutral':'green'}>{statusLabels[request.status]}</Badge><h2 className="detail-title">A record of your roadside help.</h2><div className="summary-item"><Icon name="Car"/><div><small>VEHICLE</small><strong>{request.vehicle.make} {request.vehicle.model}</strong><span>{request.vehicle.year} · {request.vehicle.colour} · {request.vehicle.plate}</span></div></div><div className="summary-item"><Icon name="MapPin"/><div><small>ASSISTANCE LOCATION</small><strong>{request.location.address}</strong></div></div><div className="summary-item"><Icon name="Wrench"/><div><small>PROBLEM DESCRIPTION</small><strong>{request.problem}</strong></div></div>{request.providerId&&<ProviderCard providerId={request.providerId}/>}<div className="notice"><Icon name="ShieldCheck"/><p>This was a simulated request. No actual provider or emergency service was dispatched.</p></div></Card><Card><h3>{request.payment?'Your payment':'Request estimate'}</h3><PriceBreakdown request={request}/>{request.payment?<><Badge><Icon name="CheckCircle2" size={14}/> Paid by {request.payment.method}</Badge><ButtonLink className="full-width spaced" to={`/receipt?id=${request.id}`} icon="FileText">View receipt</ButtonLink>{request.rating&&<div className="review-summary"><span className="star-text">{'★'.repeat(request.rating)}</span><p>{request.review||'Thank you for sharing your rating.'}</p></div>}</>:request.status==='cancelled'?<p className="notice">This request was cancelled. Nothing was charged.</p>:<ButtonLink className="full-width" to={request.status==='completed'?'/payment':'/tracking'}><span onClick={()=>store.set({activeId:request.id})}>Continue request</span><Icon name="ArrowRight"/></ButtonLink>}</Card></div></>;}
