import React,{useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import {config} from '../config/app.ts';
import {getTrackingData} from '../services/mockService.ts';
import {locations} from '../data/mockData.ts';
import {Icon} from './ui.tsx';
export function MapCard({request,location=locations[0],large=false}:any){const container=useRef<HTMLDivElement>(null);const map=useRef<any>(null);const provider=useRef<any>(null);const [tileError,setTileError]=useState(false);const loc=request?.location||location;const data=request?getTrackingData(request):null;
useEffect(()=>{if(!container.current)return;const instance=L.map(container.current,{zoomControl:false,scrollWheelZoom:false}).setView(loc.coordinates,14);map.current=instance;const tiles=L.tileLayer(config.map.tileUrl,{attribution:config.map.attribution,maxZoom:19}).addTo(instance);tiles.on('tileerror',()=>setTileError(true));tiles.on('tileload',()=>setTileError(false));L.control.zoom({position:'bottomright'}).addTo(instance);L.marker(loc.coordinates,{icon:L.divIcon({className:'customer-map-icon',html:'<span></span>',iconSize:[25,25],iconAnchor:[12,12]})}).addTo(instance).bindPopup('Your assistance location');if(request){const t=getTrackingData(request);L.polyline(t.route,{color:'#0B6B3A',weight:5,opacity:.8,lineCap:'round',dashArray:'8 7'}).addTo(instance);provider.current=L.marker(t.position,{icon:L.divIcon({className:'provider-map-icon',html:'<span>↗</span>',iconSize:[36,36],iconAnchor:[18,18]})}).addTo(instance).bindPopup('Simulated provider');instance.fitBounds(L.latLngBounds(t.route).pad(.22));}const ro=new ResizeObserver(()=>instance.invalidateSize());ro.observe(container.current);return()=>{ro.disconnect();instance.remove();map.current=null;provider.current=null;};},[loc.coordinates[0],loc.coordinates[1],request?.id]);
useEffect(()=>{if(data&&provider.current)provider.current.setLatLng(data.position);},[request?.progress]);
return <div className={`map-card ${large?'large':''}`}><div className="map-canvas" ref={container} role="region" aria-label={`Interactive map of ${loc.name}`}/><div className="map-location"><span className="green-dot"/><span>{loc.name}</span><span className="map-demo">SIMULATED</span></div>{tileError&&<div className="map-error">Map tiles unavailable. The simulated route and markers still work.</div>}<button className="map-recenter icon-button" aria-label="Recenter map" onClick={()=>map.current?.setView(loc.coordinates,14)}><Icon name="LocateFixed"/></button>{request&&<div className="map-legend"><span><i className="green-dot"/> You</span><span><i className="amber-dot"/> Your provider</span></div>}</div>;}
