import React,{useEffect,useRef} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,ArrowLeft,ArrowUpRight,Check,CheckCheck,CheckCircle2,ChevronRight,ChevronDown,MapPin,Navigation,Truck,Car,CarFront,CircleDot,BatteryCharging,Fuel,Gauge,Wrench,KeyRound,ShieldCheck,Clock,Star,Phone,MessageCircle,Menu,X,Sun,Moon,Home,History,User,Settings,LogOut,LifeBuoy,AlertTriangle,WifiOff,RefreshCw,Loader2,Plus,Minus,CreditCard,Landmark,Banknote,Download,FileText,Bell,Heart,Radio,LocateFixed,Route,SlidersHorizontal,Play,Pause,Briefcase,CheckCircle,Mail,Map,Search,HelpCircle,ExternalLink,Lock,Users,Zap,Headphones,Trash2,Send,MoveRight} from 'lucide-react';
import {config,money,date} from '../config/app.ts';
import {services,providers,statusLabels} from '../data/mockData.ts';
import type {Request,Service} from '../types/index.ts';
const icons={ArrowRight,ArrowLeft,ArrowUpRight,Check,CheckCheck,CheckCircle2,ChevronRight,ChevronDown,MapPin,Navigation,Truck,Car,CarFront,CircleDot,BatteryCharging,Fuel,Gauge,Wrench,KeyRound,ShieldCheck,Clock,Star,Phone,MessageCircle,Menu,X,Sun,Moon,Home,History,User,Settings,LogOut,LifeBuoy,AlertTriangle,WifiOff,RefreshCw,Loader2,Plus,Minus,CreditCard,Landmark,Banknote,Download,FileText,Bell,Heart,Radio,LocateFixed,Route,SlidersHorizontal,Play,Pause,Briefcase,CheckCircle,Mail,Map,Search,HelpCircle,ExternalLink,Lock,Users,Zap,Headphones,Trash2,Send,MoveRight};
export function Icon({name,size=20,...props}:{name:string;size?:number;[key:string]:any}){const Component=icons[name]||Wrench;return <Component size={size} strokeWidth={1.8} aria-hidden="true" {...props}/>;}
export function Logo({light=false}:{light?:boolean}){return <Link to="/" className={`logo ${light?'logo-light':''}`} aria-label={`${config.name} home`}><span className="brand-symbol">A<Icon name="ArrowUpRight" size={19}/></span><span>{config.name}<span className="logo-dot">.</span></span></Link>;}
export function Button({children,variant='primary',icon,loading=false,...props}:any){return <button className={`btn ${variant} ${props.className||''}`} {...props} disabled={loading||props.disabled} aria-busy={loading}>{loading?<Icon name="Loader2" className="spin"/>:icon&&<Icon name={icon}/>} {children}</button>;}
export function ButtonLink({children,to,variant='primary',icon,className=''}:any){return <Link className={`btn ${variant} ${className}`} to={to}>{children}{icon&&<Icon name={icon}/>}</Link>;}
export function Card({children,className='',...props}:any){return <section className={`card ${className}`} {...props}>{children}</section>;}
export function Field({label,error,...props}:any){const id=props.id||props.name;return <label className="field" htmlFor={id}><span>{label}</span><input id={id} {...props}/>{error&&<small className="field-error">{error}</small>}</label>;}
export function Badge({children,tone='green'}:any){return <span className={`badge ${tone}`}>{children}</span>;}
export function DemoLabel(){return <span className="demo-label"><span/> DEMO / SIMULATED</span>;}
export function ErrorMessage({message,retry}:any){if(!message)return null;return <div className="error-message" role="alert"><Icon name="AlertTriangle"/><div><strong>Something went wrong</strong><p>{message}</p>{retry&&<button className="text-button" onClick={retry}>Try again <Icon name="RefreshCw" size={14}/></button>}</div></div>;}
export function Skeleton({lines=3}:any){return <div aria-label="Loading" aria-busy="true" className="skeleton-stack">{Array.from({length:lines},(_,i)=><div key={i} className="skeleton"/>)}</div>;}
export function EmptyState({title='Nothing here just yet',description='Your next journey starts here.',action='Request assistance',to='/services',icon='Route'}:any){return <div className="empty-state"><span className="icon-tile"><Icon name={icon} size={30}/></span><h2>{title}</h2><p>{description}</p><ButtonLink to={to}>{action}<Icon name="ArrowRight"/></ButtonLink></div>;}
export function PageHeading({eyebrow,title,description,action}:any){return <header className="page-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>;}
export function ServiceCard({service,compact=false,onSelect}: {service:Service;compact?:boolean;onSelect?:()=>void}){return <Link to={`/request?service=${service.id}`} className={`service-card ${compact?'compact':''}`} onClick={onSelect}><span className="icon-tile"><Icon name={service.icon} size={26}/></span><h3>{service.name}</h3><p>{service.description}</p><div className="service-bottom"><span>From <strong>{money(service.base)}</strong></span><Icon name="ArrowUpRight" size={18}/></div>{!compact&&<small className="service-eta"><Icon name="Clock" size={13}/>{service.eta} estimated arrival</small>}</Link>;}
export function ProviderCard({providerId='daniel',children}:any){const p=providers.find(p=>p.id===providerId)||providers[0];return <div className="provider-card"><div className="provider-profile"><div className="avatar provider-avatar">{p.initials}<span><Icon name="Check" size={11}/></span></div><div><h3>{p.name} <Icon name="ShieldCheck" size={16}/></h3><p><Icon name="Star" size={14} className="star-filled"/> <strong>{p.rating}</strong> <span>· {p.jobs} completed jobs</span></p></div></div><div className="vehicle-line"><Icon name="Truck"/><span>{p.vehicle}</span><span className="plate">{p.plate}</span></div>{children}</div>;}
export function RequestCard({request}: {request:Request}){const service=services.find(s=>s.id===request.serviceId)!;return <Link to={`/history/${request.id}`} className="request-card"><span className="icon-tile"><Icon name={service.icon}/></span><div className="request-main"><h3>{service.name}</h3><p>{date(request.createdAt)} <span>· {request.location.name}</span></p></div><div className="request-end"><strong>{money(request.total)}</strong><Badge tone={request.status==='completed'?'green':request.status==='cancelled'?'neutral':'amber'}>{statusLabels[request.status]}</Badge></div><Icon name="ChevronRight" size={18}/></Link>;}
export function PriceBreakdown({request,serviceId}:any){const s=services.find(s=>s.id===(request?.serviceId||serviceId))||services[0];return <div className="price-breakdown"><div><span>Base service · {s.name}</span><strong>{money(s.base)}</strong></div><div><span>Travel & call-out fee</span><strong>{money(s.distanceCharge)}</strong></div><div><span>Additional charges</span><strong>{money(0)}</strong></div><div className="price-total"><span>{request?.payment?'Total paid':'Estimated total'}</span><strong>{money(request?.total||s.base+s.distanceCharge)}</strong></div></div>;}
export function RatingStars({value,onChange}:any){return <div className="rating-stars" role="group" aria-label="Rate your experience">{[1,2,3,4,5].map(n=><button key={n} aria-label={`${n} star${n>1?'s':''}`} aria-pressed={value>=n} className={value>=n?'selected':''} onClick={()=>onChange(n)}><Icon name="Star" size={36}/></button>)}</div>;}
export function Modal({title,children,onClose}:any){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const focusable=ref.current?.querySelectorAll<HTMLElement>('button,input,textarea,a[href]');if(!focusable?.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=previousOverflow;document.removeEventListener('keydown',key);previous?.focus();};},[]);return <div className="modal-backdrop" onClick={e=>e.target===e.currentTarget&&onClose()}><div className="modal card" ref={ref} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="section-heading"><h2 id="modal-title">{title}</h2><button className="icon-button" aria-label="Close modal" onClick={onClose}><Icon name="X"/></button></div>{children}</div></div>;}
